version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "installing something"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
      - npm install
  build:
    commands:
      - npm run build
      - grep -Fq "Application is running" dist/app.js
  post_build:
    commands:
      - echo "we are in the post build phase"

artifacts:
  # Thư mục chứa code sau build
  base-directory: dist
  files:
    - '**/*'  # đẩy tất cả file trong dist lên S3